packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.13.4
  '@orpc/openapi': ^1.13.4
  '@orpc/server': ^1.13.4
  '@orpc/zod': ^1.13.4
  convex: ^1.31.7
  dotenv: 17.2.3
  next: ^16.0.7
  typescript: ^5.9.3
  zod: ^4.3.6
