/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as DashboardGroupsRouteImport } from './routes/dashboard/groups'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AuthVerify2faRouteImport } from './routes/_auth/verify-2fa'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardFinanceRouteRouteImport } from './routes/dashboard/finance/route'
import { Route as DashboardStatisticsIndexRouteImport } from './routes/dashboard/statistics/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardProgressionIndexRouteImport } from './routes/dashboard/progression/index'
import { Route as DashboardMembersIndexRouteImport } from './routes/dashboard/members/index'
import { Route as DashboardInventoryIndexRouteImport } from './routes/dashboard/inventory/index'
import { Route as DashboardFinanceIndexRouteImport } from './routes/dashboard/finance/index'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard/events/index'
import { Route as DashboardCoachingIndexRouteImport } from './routes/dashboard/coaching/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as DashboardStatisticsTimelineRouteImport } from './routes/dashboard/statistics/timeline'
import { Route as DashboardStatisticsSnapshotRouteImport } from './routes/dashboard/statistics/snapshot'
import { Route as DashboardStatisticsMembersRouteImport } from './routes/dashboard/statistics/members'
import { Route as DashboardSettingsTeamRouteImport } from './routes/dashboard/settings/team'
import { Route as DashboardSettingsSepaRouteImport } from './routes/dashboard/settings/sepa'
import { Route as DashboardProgressionSystemIdRouteImport } from './routes/dashboard/progression/$systemId'
import { Route as DashboardMembersNewRouteImport } from './routes/dashboard/members/new'
import { Route as DashboardMembersMemberIdRouteImport } from './routes/dashboard/members/$memberId'
import { Route as DashboardInventoryProductIdRouteImport } from './routes/dashboard/inventory/$productId'
import { Route as DashboardFinanceInvoicesRouteImport } from './routes/dashboard/finance/invoices'
import { Route as DashboardEventsEventIdRouteImport } from './routes/dashboard/events/$eventId'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminOrganizationsOrgIdRouteImport } from './routes/admin/organizations/$orgId'

const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const DashboardGroupsRoute = DashboardGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AuthVerify2faRoute = AuthVerify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinanceRouteRoute = DashboardFinanceRouteRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStatisticsIndexRoute =
  DashboardStatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardProgressionIndexRoute =
  DashboardProgressionIndexRouteImport.update({
    id: '/progression/',
    path: '/progression/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardMembersIndexRoute = DashboardMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinanceIndexRoute = DashboardFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFinanceRouteRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCoachingIndexRoute = DashboardCoachingIndexRouteImport.update({
  id: '/coaching/',
  path: '/coaching/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardStatisticsTimelineRoute =
  DashboardStatisticsTimelineRouteImport.update({
    id: '/statistics/timeline',
    path: '/statistics/timeline',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStatisticsSnapshotRoute =
  DashboardStatisticsSnapshotRouteImport.update({
    id: '/statistics/snapshot',
    path: '/statistics/snapshot',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardStatisticsMembersRoute =
  DashboardStatisticsMembersRouteImport.update({
    id: '/statistics/members',
    path: '/statistics/members',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsTeamRoute = DashboardSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsSepaRoute = DashboardSettingsSepaRouteImport.update({
  id: '/sepa',
  path: '/sepa',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardProgressionSystemIdRoute =
  DashboardProgressionSystemIdRouteImport.update({
    id: '/progression/$systemId',
    path: '/progression/$systemId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardMembersNewRoute = DashboardMembersNewRouteImport.update({
  id: '/members/new',
  path: '/members/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMembersMemberIdRoute =
  DashboardMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInventoryProductIdRoute =
  DashboardInventoryProductIdRouteImport.update({
    id: '/inventory/$productId',
    path: '/inventory/$productId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardFinanceInvoicesRoute =
  DashboardFinanceInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => DashboardFinanceRouteRoute,
  } as any)
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsOrgIdRoute = AdminOrganizationsOrgIdRouteImport.update({
  id: '/organizations/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/organizations': typeof OrganizationsRoute
  '/dashboard/finance': typeof DashboardFinanceRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-2fa': typeof AuthVerify2faRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/finance/invoices': typeof DashboardFinanceInvoicesRoute
  '/dashboard/inventory/$productId': typeof DashboardInventoryProductIdRoute
  '/dashboard/members/$memberId': typeof DashboardMembersMemberIdRoute
  '/dashboard/members/new': typeof DashboardMembersNewRoute
  '/dashboard/progression/$systemId': typeof DashboardProgressionSystemIdRoute
  '/dashboard/settings/sepa': typeof DashboardSettingsSepaRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/statistics/members': typeof DashboardStatisticsMembersRoute
  '/dashboard/statistics/snapshot': typeof DashboardStatisticsSnapshotRoute
  '/dashboard/statistics/timeline': typeof DashboardStatisticsTimelineRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/dashboard/coaching/': typeof DashboardCoachingIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
  '/dashboard/progression/': typeof DashboardProgressionIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/statistics/': typeof DashboardStatisticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organizations': typeof OrganizationsRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-2fa': typeof AuthVerify2faRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/finance/invoices': typeof DashboardFinanceInvoicesRoute
  '/dashboard/inventory/$productId': typeof DashboardInventoryProductIdRoute
  '/dashboard/members/$memberId': typeof DashboardMembersMemberIdRoute
  '/dashboard/members/new': typeof DashboardMembersNewRoute
  '/dashboard/progression/$systemId': typeof DashboardProgressionSystemIdRoute
  '/dashboard/settings/sepa': typeof DashboardSettingsSepaRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/statistics/members': typeof DashboardStatisticsMembersRoute
  '/dashboard/statistics/snapshot': typeof DashboardStatisticsSnapshotRoute
  '/dashboard/statistics/timeline': typeof DashboardStatisticsTimelineRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/dashboard/coaching': typeof DashboardCoachingIndexRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/finance': typeof DashboardFinanceIndexRoute
  '/dashboard/inventory': typeof DashboardInventoryIndexRoute
  '/dashboard/members': typeof DashboardMembersIndexRoute
  '/dashboard/progression': typeof DashboardProgressionIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/statistics': typeof DashboardStatisticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/organizations': typeof OrganizationsRoute
  '/dashboard/finance': typeof DashboardFinanceRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-2fa': typeof AuthVerify2faRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/groups': typeof DashboardGroupsRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard/events/$eventId': typeof DashboardEventsEventIdRoute
  '/dashboard/finance/invoices': typeof DashboardFinanceInvoicesRoute
  '/dashboard/inventory/$productId': typeof DashboardInventoryProductIdRoute
  '/dashboard/members/$memberId': typeof DashboardMembersMemberIdRoute
  '/dashboard/members/new': typeof DashboardMembersNewRoute
  '/dashboard/progression/$systemId': typeof DashboardProgressionSystemIdRoute
  '/dashboard/settings/sepa': typeof DashboardSettingsSepaRoute
  '/dashboard/settings/team': typeof DashboardSettingsTeamRoute
  '/dashboard/statistics/members': typeof DashboardStatisticsMembersRoute
  '/dashboard/statistics/snapshot': typeof DashboardStatisticsSnapshotRoute
  '/dashboard/statistics/timeline': typeof DashboardStatisticsTimelineRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/dashboard/coaching/': typeof DashboardCoachingIndexRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/finance/': typeof DashboardFinanceIndexRoute
  '/dashboard/inventory/': typeof DashboardInventoryIndexRoute
  '/dashboard/members/': typeof DashboardMembersIndexRoute
  '/dashboard/progression/': typeof DashboardProgressionIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/statistics/': typeof DashboardStatisticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/organizations'
    | '/dashboard/finance'
    | '/dashboard/settings'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-2fa'
    | '/account/profile'
    | '/account/security'
    | '/admin/audit-log'
    | '/dashboard/account'
    | '/dashboard/billing'
    | '/dashboard/groups'
    | '/account/'
    | '/admin/'
    | '/dashboard/'
    | '/admin/organizations/$orgId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/events/$eventId'
    | '/dashboard/finance/invoices'
    | '/dashboard/inventory/$productId'
    | '/dashboard/members/$memberId'
    | '/dashboard/members/new'
    | '/dashboard/progression/$systemId'
    | '/dashboard/settings/sepa'
    | '/dashboard/settings/team'
    | '/dashboard/statistics/members'
    | '/dashboard/statistics/snapshot'
    | '/dashboard/statistics/timeline'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/dashboard/coaching/'
    | '/dashboard/events/'
    | '/dashboard/finance/'
    | '/dashboard/inventory/'
    | '/dashboard/members/'
    | '/dashboard/progression/'
    | '/dashboard/settings/'
    | '/dashboard/statistics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/organizations'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-2fa'
    | '/account/profile'
    | '/account/security'
    | '/admin/audit-log'
    | '/dashboard/account'
    | '/dashboard/billing'
    | '/dashboard/groups'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/admin/organizations/$orgId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/events/$eventId'
    | '/dashboard/finance/invoices'
    | '/dashboard/inventory/$productId'
    | '/dashboard/members/$memberId'
    | '/dashboard/members/new'
    | '/dashboard/progression/$systemId'
    | '/dashboard/settings/sepa'
    | '/dashboard/settings/team'
    | '/dashboard/statistics/members'
    | '/dashboard/statistics/snapshot'
    | '/dashboard/statistics/timeline'
    | '/admin/organizations'
    | '/admin/users'
    | '/dashboard/coaching'
    | '/dashboard/events'
    | '/dashboard/finance'
    | '/dashboard/inventory'
    | '/dashboard/members'
    | '/dashboard/progression'
    | '/dashboard/settings'
    | '/dashboard/statistics'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/_auth'
    | '/organizations'
    | '/dashboard/finance'
    | '/dashboard/settings'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-2fa'
    | '/account/profile'
    | '/account/security'
    | '/admin/audit-log'
    | '/dashboard/account'
    | '/dashboard/billing'
    | '/dashboard/groups'
    | '/account/'
    | '/admin/'
    | '/dashboard/'
    | '/admin/organizations/$orgId'
    | '/admin/users/$userId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard/events/$eventId'
    | '/dashboard/finance/invoices'
    | '/dashboard/inventory/$productId'
    | '/dashboard/members/$memberId'
    | '/dashboard/members/new'
    | '/dashboard/progression/$systemId'
    | '/dashboard/settings/sepa'
    | '/dashboard/settings/team'
    | '/dashboard/statistics/members'
    | '/dashboard/statistics/snapshot'
    | '/dashboard/statistics/timeline'
    | '/admin/organizations/'
    | '/admin/users/'
    | '/dashboard/coaching/'
    | '/dashboard/events/'
    | '/dashboard/finance/'
    | '/dashboard/inventory/'
    | '/dashboard/members/'
    | '/dashboard/progression/'
    | '/dashboard/settings/'
    | '/dashboard/statistics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OrganizationsRoute: typeof OrganizationsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/dashboard/groups': {
      id: '/dashboard/groups'
      path: '/groups'
      fullPath: '/dashboard/groups'
      preLoaderRoute: typeof DashboardGroupsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/_auth/verify-2fa': {
      id: '/_auth/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof AuthVerify2faRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/statistics/': {
      id: '/dashboard/statistics/'
      path: '/statistics'
      fullPath: '/dashboard/statistics/'
      preLoaderRoute: typeof DashboardStatisticsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/progression/': {
      id: '/dashboard/progression/'
      path: '/progression'
      fullPath: '/dashboard/progression/'
      preLoaderRoute: typeof DashboardProgressionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members/': {
      id: '/dashboard/members/'
      path: '/members'
      fullPath: '/dashboard/members/'
      preLoaderRoute: typeof DashboardMembersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inventory/': {
      id: '/dashboard/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory/'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finance/': {
      id: '/dashboard/finance/'
      path: '/'
      fullPath: '/dashboard/finance/'
      preLoaderRoute: typeof DashboardFinanceIndexRouteImport
      parentRoute: typeof DashboardFinanceRouteRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/coaching/': {
      id: '/dashboard/coaching/'
      path: '/coaching'
      fullPath: '/dashboard/coaching/'
      preLoaderRoute: typeof DashboardCoachingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/statistics/timeline': {
      id: '/dashboard/statistics/timeline'
      path: '/statistics/timeline'
      fullPath: '/dashboard/statistics/timeline'
      preLoaderRoute: typeof DashboardStatisticsTimelineRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/statistics/snapshot': {
      id: '/dashboard/statistics/snapshot'
      path: '/statistics/snapshot'
      fullPath: '/dashboard/statistics/snapshot'
      preLoaderRoute: typeof DashboardStatisticsSnapshotRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/statistics/members': {
      id: '/dashboard/statistics/members'
      path: '/statistics/members'
      fullPath: '/dashboard/statistics/members'
      preLoaderRoute: typeof DashboardStatisticsMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/team': {
      id: '/dashboard/settings/team'
      path: '/team'
      fullPath: '/dashboard/settings/team'
      preLoaderRoute: typeof DashboardSettingsTeamRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/sepa': {
      id: '/dashboard/settings/sepa'
      path: '/sepa'
      fullPath: '/dashboard/settings/sepa'
      preLoaderRoute: typeof DashboardSettingsSepaRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/progression/$systemId': {
      id: '/dashboard/progression/$systemId'
      path: '/progression/$systemId'
      fullPath: '/dashboard/progression/$systemId'
      preLoaderRoute: typeof DashboardProgressionSystemIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members/new': {
      id: '/dashboard/members/new'
      path: '/members/new'
      fullPath: '/dashboard/members/new'
      preLoaderRoute: typeof DashboardMembersNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members/$memberId': {
      id: '/dashboard/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/dashboard/members/$memberId'
      preLoaderRoute: typeof DashboardMembersMemberIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inventory/$productId': {
      id: '/dashboard/inventory/$productId'
      path: '/inventory/$productId'
      fullPath: '/dashboard/inventory/$productId'
      preLoaderRoute: typeof DashboardInventoryProductIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finance/invoices': {
      id: '/dashboard/finance/invoices'
      path: '/invoices'
      fullPath: '/dashboard/finance/invoices'
      preLoaderRoute: typeof DashboardFinanceInvoicesRouteImport
      parentRoute: typeof DashboardFinanceRouteRoute
    }
    '/dashboard/events/$eventId': {
      id: '/dashboard/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/dashboard/events/$eventId'
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/$orgId': {
      id: '/admin/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/admin/organizations/$orgId'
      preLoaderRoute: typeof AdminOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrganizationsOrgIdRoute: typeof AdminOrganizationsOrgIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrganizationsOrgIdRoute: AdminOrganizationsOrgIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DashboardFinanceRouteRouteChildren {
  DashboardFinanceInvoicesRoute: typeof DashboardFinanceInvoicesRoute
  DashboardFinanceIndexRoute: typeof DashboardFinanceIndexRoute
}

const DashboardFinanceRouteRouteChildren: DashboardFinanceRouteRouteChildren = {
  DashboardFinanceInvoicesRoute: DashboardFinanceInvoicesRoute,
  DashboardFinanceIndexRoute: DashboardFinanceIndexRoute,
}

const DashboardFinanceRouteRouteWithChildren =
  DashboardFinanceRouteRoute._addFileChildren(
    DashboardFinanceRouteRouteChildren,
  )

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsSepaRoute: typeof DashboardSettingsSepaRoute
  DashboardSettingsTeamRoute: typeof DashboardSettingsTeamRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsSepaRoute: DashboardSettingsSepaRoute,
    DashboardSettingsTeamRoute: DashboardSettingsTeamRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardFinanceRouteRoute: typeof DashboardFinanceRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardGroupsRoute: typeof DashboardGroupsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute
  DashboardInventoryProductIdRoute: typeof DashboardInventoryProductIdRoute
  DashboardMembersMemberIdRoute: typeof DashboardMembersMemberIdRoute
  DashboardMembersNewRoute: typeof DashboardMembersNewRoute
  DashboardProgressionSystemIdRoute: typeof DashboardProgressionSystemIdRoute
  DashboardStatisticsMembersRoute: typeof DashboardStatisticsMembersRoute
  DashboardStatisticsSnapshotRoute: typeof DashboardStatisticsSnapshotRoute
  DashboardStatisticsTimelineRoute: typeof DashboardStatisticsTimelineRoute
  DashboardCoachingIndexRoute: typeof DashboardCoachingIndexRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardMembersIndexRoute: typeof DashboardMembersIndexRoute
  DashboardProgressionIndexRoute: typeof DashboardProgressionIndexRoute
  DashboardStatisticsIndexRoute: typeof DashboardStatisticsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardFinanceRouteRoute: DashboardFinanceRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardGroupsRoute: DashboardGroupsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
  DashboardInventoryProductIdRoute: DashboardInventoryProductIdRoute,
  DashboardMembersMemberIdRoute: DashboardMembersMemberIdRoute,
  DashboardMembersNewRoute: DashboardMembersNewRoute,
  DashboardProgressionSystemIdRoute: DashboardProgressionSystemIdRoute,
  DashboardStatisticsMembersRoute: DashboardStatisticsMembersRoute,
  DashboardStatisticsSnapshotRoute: DashboardStatisticsSnapshotRoute,
  DashboardStatisticsTimelineRoute: DashboardStatisticsTimelineRoute,
  DashboardCoachingIndexRoute: DashboardCoachingIndexRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardMembersIndexRoute: DashboardMembersIndexRoute,
  DashboardProgressionIndexRoute: DashboardProgressionIndexRoute,
  DashboardStatisticsIndexRoute: DashboardStatisticsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerify2faRoute: typeof AuthVerify2faRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerify2faRoute: AuthVerify2faRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OrganizationsRoute: OrganizationsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
