import type { AuditEventDefinition } from "./types";

export const auditEvents = {
  SIGN_UP: {
    code: "SIGN_UP",
    name: "Sign up",
    category: "auth",
    severity: "info",
    targetKinds: ["user"],
    deniable: true,
    description: "A user account was created.",
  },
  SIGN_IN: {
    code: "SIGN_IN",
    name: "Sign in",
    category: "auth",
    severity: "info",
    targetKinds: ["user", "session"],
    deniable: true,
    description: "A user attempted to sign in.",
  },
  ORG_CREATE: {
    code: "ORG_CREATE",
    name: "Organisation erstellt",
    category: "organization",
    severity: "info",
    targetKinds: ["organization"],
    deniable: true,
    description: "An organization was created.",
  },
  ORG_MEMBER_INVITE: {
    code: "ORG_MEMBER_INVITE",
    name: "Org-Mitglied eingeladen",
    category: "organization",
    severity: "info",
    targetKinds: ["user"],
    deniable: true,
    description: "A user was invited to an organization.",
  },
  ORG_MEMBER_ADD: {
    code: "ORG_MEMBER_ADD",
    name: "Org-Mitglied hinzugefuegt",
    category: "organization",
    severity: "warning",
    targetKinds: ["user"],
    deniable: true,
    description: "A user was directly added to an organization.",
  },
  ORG_MEMBER_REMOVE: {
    code: "ORG_MEMBER_REMOVE",
    name: "Org-Mitglied entfernt",
    category: "organization",
    severity: "warning",
    targetKinds: ["user"],
    deniable: true,
    description: "A user was removed from an organization.",
  },
  MEMBER_CREATE: {
    code: "MEMBER_CREATE",
    name: "Mitglied erstellt",
    category: "members",
    severity: "info",
    targetKinds: ["member"],
    deniable: true,
    description: "A club member record was created.",
  },
  MEMBER_UPDATE: {
    code: "MEMBER_UPDATE",
    name: "Mitglied bearbeitet",
    category: "members",
    severity: "info",
    targetKinds: ["member"],
    deniable: true,
    description: "A club member record was updated.",
  },
  MEMBER_CONTRACT_UPDATE: {
    code: "MEMBER_CONTRACT_UPDATE",
    name: "Vertrag bearbeitet",
    category: "members",
    severity: "warning",
    targetKinds: ["member"],
    deniable: true,
    description: "A member contract was updated.",
  },
  MEMBER_CONTRACT_CANCEL: {
    code: "MEMBER_CONTRACT_CANCEL",
    name: "Vertrag gekuendigt",
    category: "members",
    severity: "warning",
    targetKinds: ["member"],
    deniable: true,
    description: "A member contract was cancelled.",
  },
  MEMBER_GROUP_ASSIGN: {
    code: "MEMBER_GROUP_ASSIGN",
    name: "Gruppe zugewiesen",
    category: "members",
    severity: "info",
    targetKinds: ["member", "group"],
    deniable: true,
    description: "A member was assigned to a group.",
  },
  MEMBER_GROUP_UPDATE: {
    code: "MEMBER_GROUP_UPDATE",
    name: "Gruppenmitgliedschaft bearbeitet",
    category: "members",
    severity: "info",
    targetKinds: ["member", "group"],
    deniable: true,
    description: "A member group assignment was updated.",
  },
  MEMBER_GROUP_REMOVE: {
    code: "MEMBER_GROUP_REMOVE",
    name: "Gruppenmitgliedschaft entfernt",
    category: "members",
    severity: "info",
    targetKinds: ["member", "group"],
    deniable: true,
    description: "A member group assignment was removed.",
  },
  GROUP_CREATE: {
    code: "GROUP_CREATE",
    name: "Gruppe erstellt",
    category: "groups",
    severity: "info",
    targetKinds: ["group"],
    deniable: true,
    description: "A group was created.",
  },
  GROUP_UPDATE: {
    code: "GROUP_UPDATE",
    name: "Gruppe bearbeitet",
    category: "groups",
    severity: "info",
    targetKinds: ["group"],
    deniable: true,
    description: "A group was updated.",
  },
  GROUP_DELETE: {
    code: "GROUP_DELETE",
    name: "Gruppe geloescht",
    category: "groups",
    severity: "warning",
    targetKinds: ["group"],
    deniable: true,
    description: "A group was deleted.",
  },
  INVENTORY_CREATE: {
    code: "INVENTORY_CREATE",
    name: "Inventarprodukt erstellt",
    category: "inventory",
    severity: "info",
    targetKinds: ["inventory"],
    deniable: true,
    description: "An inventory product was created.",
  },
  INVENTORY_UPDATE: {
    code: "INVENTORY_UPDATE",
    name: "Inventarprodukt bearbeitet",
    category: "inventory",
    severity: "info",
    targetKinds: ["inventory"],
    deniable: true,
    description: "An inventory product was updated.",
  },
  INVENTORY_DELETE: {
    code: "INVENTORY_DELETE",
    name: "Inventarprodukt geloescht",
    category: "inventory",
    severity: "warning",
    targetKinds: ["inventory"],
    deniable: true,
    description: "An inventory product was deleted.",
  },
  INVENTORY_STOCK_UPDATE: {
    code: "INVENTORY_STOCK_UPDATE",
    name: "Bestand aktualisiert",
    category: "inventory",
    severity: "info",
    targetKinds: ["inventory"],
    deniable: true,
    description: "Inventory stock was updated.",
  },
  INVENTORY_SYNC: {
    code: "INVENTORY_SYNC",
    name: "Inventar synchronisiert",
    category: "inventory",
    severity: "info",
    targetKinds: ["inventory"],
    deniable: true,
    description: "Inventory data was synchronized.",
  },
  SEPA_SETTINGS_UPDATE: {
    code: "SEPA_SETTINGS_UPDATE",
    name: "SEPA-Einstellungen bearbeitet",
    category: "billing",
    severity: "warning",
    targetKinds: ["sepa"],
    deniable: true,
    description: "SEPA settings were updated.",
  },
  SEPA_MANDATE_CREATE: {
    code: "SEPA_MANDATE_CREATE",
    name: "SEPA-Mandat erstellt",
    category: "billing",
    severity: "info",
    targetKinds: ["member", "sepa"],
    deniable: true,
    description: "A SEPA mandate was created.",
  },
  SEPA_MANDATE_REVOKE: {
    code: "SEPA_MANDATE_REVOKE",
    name: "SEPA-Mandat widerrufen",
    category: "billing",
    severity: "warning",
    targetKinds: ["member", "sepa"],
    deniable: true,
    description: "A SEPA mandate was revoked.",
  },
  CREDIT_GRANT_CREATE: {
    code: "CREDIT_GRANT_CREATE",
    name: "Gutschrift erstellt",
    category: "billing",
    severity: "warning",
    targetKinds: ["member"],
    deniable: true,
    description: "A credit grant was created.",
  },
  INVOICE_GENERATE: {
    code: "INVOICE_GENERATE",
    name: "Rechnungen generiert",
    category: "billing",
    severity: "warning",
    targetKinds: ["period"],
    deniable: true,
    description: "Invoices were generated for a period.",
  },
  INVOICE_REPLACE: {
    code: "INVOICE_REPLACE",
    name: "Rechnung ersetzt",
    category: "billing",
    severity: "warning",
    targetKinds: ["invoice"],
    deniable: true,
    description: "An invoice was replaced.",
  },
  INVOICE_VOID: {
    code: "INVOICE_VOID",
    name: "Rechnung ungueltig gemacht",
    category: "billing",
    severity: "critical",
    targetKinds: ["invoice"],
    deniable: true,
    description: "An invoice was voided.",
  },
  SEPA_BATCH_GENERATE: {
    code: "SEPA_BATCH_GENERATE",
    name: "SEPA-Batch generiert",
    category: "billing",
    severity: "warning",
    targetKinds: ["sepa"],
    deniable: true,
    description: "A SEPA batch was generated.",
  },
  SEPA_BATCH_DOWNLOAD: {
    code: "SEPA_BATCH_DOWNLOAD",
    name: "SEPA-Batch heruntergeladen",
    category: "billing",
    severity: "warning",
    targetKinds: ["sepa"],
    deniable: true,
    description: "A SEPA batch file was downloaded.",
  },
  SEPA_BATCH_MARK_DOWNLOADED: {
    code: "SEPA_BATCH_MARK_DOWNLOADED",
    name: "SEPA-Batch als heruntergeladen markiert",
    category: "billing",
    severity: "warning",
    targetKinds: ["sepa"],
    deniable: true,
    description: "A SEPA batch was manually marked as downloaded.",
  },
  SEPA_BATCH_SUPERSEDE: {
    code: "SEPA_BATCH_SUPERSEDE",
    name: "SEPA-Batch ersetzt",
    category: "billing",
    severity: "critical",
    targetKinds: ["sepa"],
    deniable: true,
    description: "A SEPA batch was superseded.",
  },
  SEPA_BATCH_VOID: {
    code: "SEPA_BATCH_VOID",
    name: "SEPA-Batch ungueltig gemacht",
    category: "billing",
    severity: "critical",
    targetKinds: ["sepa"],
    deniable: true,
    description: "A SEPA batch was voided.",
  },
  USER_BAN: {
    code: "USER_BAN",
    name: "Benutzer gesperrt",
    category: "admin",
    severity: "critical",
    targetKinds: ["user"],
    deniable: true,
    description: "A user account was banned.",
  },
  USER_UNBAN: {
    code: "USER_UNBAN",
    name: "Benutzer entsperrt",
    category: "admin",
    severity: "warning",
    targetKinds: ["user"],
    deniable: true,
    description: "A user account was unbanned.",
  },
  USER_ADMIN_GRANT: {
    code: "USER_ADMIN_GRANT",
    name: "Adminrechte vergeben",
    category: "admin",
    severity: "critical",
    targetKinds: ["user"],
    deniable: true,
    description: "Platform admin rights were granted to a user.",
  },
  USER_ADMIN_REVOKE: {
    code: "USER_ADMIN_REVOKE",
    name: "Adminrechte entzogen",
    category: "admin",
    severity: "critical",
    targetKinds: ["user"],
    deniable: true,
    description: "Platform admin rights were revoked from a user.",
  },
  USER_PASSWORD_RESET: {
    code: "USER_PASSWORD_RESET",
    name: "Passwort zurueckgesetzt",
    category: "admin",
    severity: "critical",
    targetKinds: ["user"],
    deniable: true,
    description: "A user's password was reset.",
  },
  USER_IMPERSONATE: {
    code: "USER_IMPERSONATE",
    name: "Benutzer impersoniert",
    category: "admin",
    severity: "critical",
    targetKinds: ["user"],
    deniable: true,
    description: "An admin impersonated a user.",
  },
  SESSION_REVOKE: {
    code: "SESSION_REVOKE",
    name: "Session widerrufen",
    category: "admin",
    severity: "warning",
    targetKinds: ["session"],
    deniable: true,
    description: "A single user session was revoked.",
  },
  SESSIONS_REVOKE: {
    code: "SESSIONS_REVOKE",
    name: "Alle Sessions widerrufen",
    category: "admin",
    severity: "critical",
    targetKinds: ["user"],
    deniable: true,
    description: "All sessions for a user were revoked.",
  },
  USER_DELETE: {
    code: "USER_DELETE",
    name: "Benutzer geloescht",
    category: "admin",
    severity: "critical",
    targetKinds: ["user"],
    deniable: true,
    description: "A user account was permanently deleted.",
  },
} satisfies Record<string, AuditEventDefinition>;

export type AuditEventCode = keyof typeof auditEvents;

export function getAuditEventDefinition(code: AuditEventCode) {
  return auditEvents[code];
}
