import type { Member } from "./types";

export const members: Member[] = [
	{
		id: "1",
		name: "Sarah Johnson",
		email: "sarah.johnson@example.com",
		phone: "+1 (555) 123-4567",
		groups: ["Admin", "Engineering"],
	},
	{
		id: "2",
		name: "Michael Chen",
		email: "michael.chen@example.com",
		phone: "+1 (555) 234-5678",
		groups: ["Engineering", "Design"],
	},
	{
		id: "3",
		name: "Emily Rodriguez",
		email: "emily.rodriguez@example.com",
		phone: "+1 (555) 345-6789",
		groups: ["Marketing"],
	},
	{
		id: "4",
		name: "David Kim",
		email: "david.kim@example.com",
		phone: "+1 (555) 456-7890",
		groups: ["Sales", "Marketing"],
	},
	{
		id: "5",
		name: "Jessica Williams",
		email: "jessica.williams@example.com",
		phone: "+1 (555) 567-8901",
		groups: ["Engineering"],
	},
	{
		id: "6",
		name: "James Brown",
		email: "james.brown@example.com",
		phone: "+1 (555) 678-9012",
		groups: ["Admin", "Support"],
	},
	{
		id: "7",
		name: "Maria Garcia",
		email: "maria.garcia@example.com",
		phone: "+1 (555) 789-0123",
		groups: ["Design"],
	},
	{
		id: "8",
		name: "Robert Taylor",
		email: "robert.taylor@example.com",
		phone: "+1 (555) 890-1234",
		groups: ["Engineering", "Admin"],
	},
	{
		id: "9",
		name: "Jennifer Martinez",
		email: "jennifer.martinez@example.com",
		phone: "+1 (555) 901-2345",
		groups: ["Support"],
	},
	{
		id: "10",
		name: "William Anderson",
		email: "william.anderson@example.com",
		phone: "+1 (555) 012-3456",
		groups: ["Sales"],
	},
	{
		id: "11",
		name: "Linda Thomas",
		email: "linda.thomas@example.com",
		phone: "+1 (555) 123-4568",
		groups: ["Marketing", "Design"],
	},
	{
		id: "12",
		name: "Christopher Lee",
		email: "christopher.lee@example.com",
		phone: "+1 (555) 234-5679",
		groups: ["Engineering"],
	},
	{
		id: "13",
		name: "Patricia White",
		email: "patricia.white@example.com",
		phone: "+1 (555) 345-6780",
		groups: ["Admin"],
	},
	{
		id: "14",
		name: "Daniel Harris",
		email: "daniel.harris@example.com",
		phone: "+1 (555) 456-7891",
		groups: ["Support", "Engineering"],
	},
	{
		id: "15",
		name: "Barbara Clark",
		email: "barbara.clark@example.com",
		phone: "+1 (555) 567-8902",
		groups: ["Sales", "Marketing"],
	},
	{
		id: "16",
		name: "Matthew Lewis",
		email: "matthew.lewis@example.com",
		phone: "+1 (555) 678-9013",
		groups: ["Design"],
	},
	{
		id: "17",
		name: "Susan Walker",
		email: "susan.walker@example.com",
		phone: "+1 (555) 789-0124",
		groups: ["Engineering", "Support"],
	},
	{
		id: "18",
		name: "Joseph Hall",
		email: "joseph.hall@example.com",
		phone: "+1 (555) 890-1235",
		groups: ["Marketing"],
	},
	{
		id: "19",
		name: "Karen Allen",
		email: "karen.allen@example.com",
		phone: "+1 (555) 901-2346",
		groups: ["Admin", "Sales"],
	},
	{
		id: "20",
		name: "Thomas Young",
		email: "thomas.young@example.com",
		phone: "+1 (555) 012-3457",
		groups: ["Engineering"],
	},
	{
		id: "21",
		name: "Nancy King",
		email: "nancy.king@example.com",
		phone: "+1 (555) 123-4569",
		groups: ["Design", "Marketing"],
	},
	{
		id: "22",
		name: "Charles Wright",
		email: "charles.wright@example.com",
		phone: "+1 (555) 234-5680",
		groups: ["Support"],
	},
	{
		id: "23",
		name: "Lisa Lopez",
		email: "lisa.lopez@example.com",
		phone: "+1 (555) 345-6781",
		groups: ["Sales"],
	},
	{
		id: "24",
		name: "Paul Hill",
		email: "paul.hill@example.com",
		phone: "+1 (555) 456-7892",
		groups: ["Engineering", "Admin"],
	},
	{
		id: "25",
		name: "Sandra Scott",
		email: "sandra.scott@example.com",
		phone: "+1 (555) 567-8903",
		groups: ["Marketing"],
	},
];
